<?php


namespace app\models\profile;

use app\models\user\User;
use yii\base\Model;

class ProfileInfoForm extends Model
{
    public $username;
    public $f_name;
    public $l_name;
    public $p_name;
    public $email;
    public $company;
    public $phone;

    private $_user;

    /**
     * ProfileInfoForm constructor.
     * @param User $user
     * @param array $config
     */
    public function __construct(User $user, $config = [])
    {
        if ($user){
            $this->username     = $user->username;
            $this->f_name       = $user->f_name;
            $this->l_name       = $user->l_name;
            $this->p_name       = $user->p_name;
            $this->email        = $user->email;
            $this->company      = $user->company;
            $this->phone        = $user->phone;
            $this->_user        = $user;
        }
        parent::__construct($config);
    }

    public function rules()
    {
        return [
            [['username', 'f_name', 'l_name','p_name', 'phone', 'email','phone', 'email', 'company'], 'string'],
            [['username', 'f_name', 'l_name', 'phone', 'email'], 'required', 'message'=>getRuleMessage('required')],
            [['username', 'f_name', 'l_name','p_name', 'phone', 'email','phone', 'email', 'company'], 'trim'],
            ['email', 'email', 'message' => getRuleMessage('email')],
            [['phone', 'email', 'company'], 'string', 'max' => 25, 'message'=>getRuleMessage('tooLong')],
            [['email'], 'unique', 'targetClass' => User::class, 'filter' => ['<>', 'id', $this->_user->id], 'message'=>getRuleMessage('unique_email')],
            [['username'], 'unique', 'targetClass' => User::class, 'filter' => ['<>', 'id', $this->_user->id], 'message'=>getRuleMessage('unique_username')],
        ];
    }

    public function beforeValidate()
    {
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'username' => 'Имя пользователя',
            'f_name' => 'Имя',
            'l_name' => 'Фамилия',
            'p_name' => 'Отчество',
            'email' => 'Електронная почта',
            'company' => 'Название компании',
            'phone' => 'Телефон',
        ];
    }


}